---
- hosts: all
  become: yes
  tasks:
  - name: Install apache2 webserver
    apt:
      name: apache2
      state: present
      when: ansible_os_family=="Debian"

  - name: starting apache2 websever
    service:
       name: apache2
       state: started
       when: ansible_os_family=="Debian"

  - name:  Install webserver in Red HAT
    dnf:
      name: httpd
      state: present
      when: ansible_os_family=="RedHat"

  - name: Start webserver
    service: 
       name: httpd
       state: started
       when: ansible_os_family=="RedHat""
       