---
- hosts: myWebServers
  become: yes
  tasks:
  - name: Install {{mywebpackonubuntu}} webserver
    apt:
      name: {{mywebpackonubuntu}}
      state: present
    when: ansible_os_family=="Debian"

  - name: starting {{mywebpackonubuntu}} websever
    service:
       name: {{mywebpackonubuntu}}
       state: started
    when: ansible_os_family=="Debian"

  - name:  Install webserver in {{mywebpackonredhat}}
    dnf:
      name: {{mywebpackonredhat}}
      state: present
    when: ansible_os_family=="RedHat"

  - name: Start webserver
    service: 
      name: {{mywebpackonredhat}}
      state: started
    when: ansible_os_family=="RedHat"
       